### ISSUE TITLE
Problem with installing plugin (QGIS 2.99)

### ISSUE THREAD

**Issue by scarabdesign** [sourcepole/qgis-openlayers-plugin#32]
I have built QGIS 2.99 from source and went looking for this plugin which a coworker was using on QGIS 2.4. According to this [page](http://plugins.qgis.org/plugins/openlayers_plugin/version/1.4.3/),  the max version of QGIS is 2.99, but when I try to load it (by downloading the zip and using "Install plugin from ZIP"), it gives the error pasted below. QGIS seems to be using Python 3; is this plugin compatible with Python 3? If not, is there a way I can downgrade Python that QGIS is using?

```
Couldn't load plugin 'openlayers_plugin' due to an error when calling its classFactory() method 

ImportError: cannot import name 'OpenlayersPlugin' 
Traceback (most recent call last):
  File "/usr/local/share/qgis/python/qgis/utils.py", line 337, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/dev/.qgis3/python/plugins/openlayers_plugin/__init__.py", line 25, in classFactory
    from openlayers_plugin import OpenlayersPlugin
ImportError: cannot import name 'OpenlayersPlugin'


Python version: 3.5.2 (default, Nov 17 2016, 17:05:23) [GCC 5.4.0 20160609] 
QGIS version: 2.99.0-Master Master, 258c872 

Python Path:
/usr/local/share/qgis/python/plugins/processing
/usr/local/share/qgis/python
/home/dev/.qgis3/python
/home/dev/.qgis3/python/plugins
/usr/local/share/qgis/python/plugins
/usr/lib/python35.zip
/usr/lib/python3.5
/usr/lib/python3.5/plat-x86_64-linux-gnu
/usr/lib/python3.5/lib-dynload
/home/dev/.local/lib/python3.5/site-packages
/usr/local/lib/python3.5/dist-packages
/usr/lib/python3/dist-packages
/home/dev/.qgis3//python
```

**Comment by james2432** [comment]
Same thing for me as well

**Comment by Greilachelous** [comment]
Same, please give us some information!

**Comment by Greilachelous** [comment]
@scarabdesign @james2432 Have anybody here some workout?

**Comment by james2432** [comment]
There's no work around. As most python developers... the code is not python 3 compatible. The develper needs to make it compatible before this is ever usable again

**Comment by Greilachelous** [comment]
@james2432 OK, no matter as I soon as I can, I will change the code to conform to Python 3 my own. 
We can't know what's going on with the developer.
I will inform you here when it will be fixed.
Btw. how did you managed to solve the clustering for now?

**Comment by djSupport** [comment]
I'm on 2.18.11 it appeared to lose its modifcations somehow and on re-doing the actions it does not want to show a map anymore, it's not showing any errors

**Comment by djSupport** [comment]
Ah, damn sorry that was referring to the OS Map layer

**Comment by pka** [comment]
Will will port the plugin to QGIS 3.0 as soon as the API is stable. Probably after feature freeze.

**Comment by pka** [comment]
The port to QGIS 3 is tracked in #37

**Comment by Karlheinzniebuhr** [comment]
same issue

**Comment by pka** [comment]
The QGIS 3 port (see #37) requires a version >= 3.0.1

**Comment by emilycoco** [comment]
For anyone else ending up here from google, the experimental >2.0.0 versions do work with python 3.
