### ISSUE TITLE
port to qt5?

### ISSUE THREAD

**Issue by attractedtofire** [sourcepole/qgis-openlayers-plugin#37]
Are there any plans to port the plugin to QT5 in the future? QtWebKit for Qt 4 seems to have been unmaintained for quite some time now.

**Comment by pka** [comment]
We will port the plugin to QGIS 3 (QT5+Python 3) as soon as the API is freezed.

**Comment by fvalenduc** [comment]
According to this: https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule
The freeze occured on  27/10/2017, or I am wrong ?
Any news on the port to QT 5 ?

**Comment by pka** [comment]
Unfortunately, the freeze is neither a feature freeze nor an API freeze. Core API is still in flux.

**Comment by h4k1m0u** [comment]
Sorry I'm quite new around, but I couldn't find any information about the date when the API will freeze (is it around when QGIS3 is out, 23/02/2018 according to the [roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html))?

**Comment by brylie** [comment]
Now that QGIS 3.0 has been released, it seems like a good time to start this upgrade process. What tasks are involved? How may I help?

**Comment by pka** [comment]
The release finally happenend, hurray! There are two main tasks: porting the JavaScript based functionality to QGIS 3 and migrating the GDAL layers to the new XYZ layers. Help on any tasks would be greatly appreciated! Currently we're working on customer projects with higher priority, but if there is a PR, we would merge as quick as possible.

**Comment by brylie** [comment]
> here are two main tasks: porting the JavaScript based functionality to QGIS 3 and migrating the GDAL layers to the new XYZ layers. Help on any tasks would be greatly appreciated!

@pka, would you mind opening some explicit tasks in this issue queue, so we can tackle the upgrade incrementally?

**Comment by pka** [comment]
Ok, I made a separate issue #45 for the XYZ migration, which is not strictly necessarily. Let's track the main migration to QGIS 3 in this ticket.

**Comment by brylie** [comment]
> porting the JavaScript based functionality to QGIS 3

Since we will be tracking the QGIS 3 migration in this ticket, would you explain a bit more about the changes necessary for the JavaScript functionality? I am new to QGIS development, and would appreciate guidance in this matter. Are there some example files or methods that we should be considering?

**Comment by Miriup** [comment]
I haven't developed for QGIS yet, but I also previously took a look at upgrading the OpenLayers plugin to QT5. I would start with:

-  installing QGIS3
- checking out OpenLayers plugin from github into the plugin directory
- immediately replacing all references to "PyQt4" to "PyQt5"

Then you load the plugin and see where it fails, then google for the error. Most of the times someone will have faced that particular issue already in some other software. Follow their suggestions. Then correct the OpenLayers plugin and move onto the next quirk. Something like that. ;-)

**Comment by pka** [comment]
@brylie This plugin will not be the easiest one to start with QGIS development, but if you're fluent with Python then it's certainly possible. The best starting point for porting plugins is https://github.com/qgis/QGIS/wiki/Plugin-migration-to-QGIS-3

**Comment by fvalenduc** [comment]
I tried it on windows and it fails with this error:

Impossible de charger l'extension 'openlayers_plugin' provoque une erreur lors de l'appel à sa méthode classFactory() 

ImportError: cannot import name 'OpenlayersPlugin' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/François/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\openlayers_plugin\__init__.py", line 25, in classFactory
    from openlayers_plugin import OpenlayersPlugin
ImportError: cannot import name 'OpenlayersPlugin'


Version de Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
Version de QGIS : 3.0.1-Girona Girona, a86bec25eb 

Chemin Python :
C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python
C:/Users/François/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/François/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.0\bin\python36.zip
C:\PROGRA~1\QGIS3~1.0\apps\Python36\DLLs
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib
C:\Program Files\QGIS 3.0\bin
C:\PROGRA~1\QGIS3~1.0\apps\Python36
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages
C:/Users/François/AppData/Roaming/QGIS/QGIS3\profiles\default/python%                                                                                       

I downloaded the git tree and I ran make package VERSION=v1.4.8 (on linux) to create the zip file. Did I do something wrong ?

**Comment by fvalenduc** [comment]
I indeed did something wrong, 1.4.8 was not the correct version... With the correct version, It seems to work ok, after very limited testing.

**Comment by pka** [comment]
Port to QGIS 3 is now published as *experimental* [version 2.0.0](http://plugins.qgis.org/plugins/openlayers_plugin/version/2.0.0/). Please test and give feedback in this ticket.

**Comment by HusseinKabbout** [comment]
Since there hasn't been much feedback in this issue I will be closing it. Please create a new issue if you encounter any problems or have any questions regarding the plugin.
