### ISSUE TITLE
thunderforest maplayers only appears in black

### ISSUE THREAD

**Issue by onlyMaps** [sourcepole/qgis-openlayers-plugin#40]
Any chance to get information or help how to get my API key working in your Plugin?
My API key works fine on this map example: https://www.onlymaps.dk/ocm/ocm.html
But all the thunderforest maplayers only appears in black in Qgis when using the OpenLayers Plugin.

QGIS-version 2.18.14
OpenLayers Plugin 1.4.6

![api_2](https://user-images.githubusercontent.com/6785759/34204872-96e37e8a-e580-11e7-8679-1a2b9ffdf2dc.JPG)

**Comment by pka** [comment]
Do you have an internet proxy in place. I saw black or near black maps with unsupported proxy types before.

**Comment by HusseinKabbout** [comment]
This issue will be closed, because the qgis2 version of this plugin is not maintained anymore.
