### ISSUE TITLE
Google Satellite High Zoom Issue

### ISSUE THREAD

**Issue by gambonet** [sourcepole/qgis-openlayers-plugin#41]
Hi guys, 

Actually I'm using the QGIS Version 2.18.12, I dont know if you made an update of Open Layer Plugin in the past days, but today with the Google Maps - Google Satellite I have some serious problem with the zoom. 

if I zoom over the scale 1: 1150, the satellite image loses the correct references and go out of phase with the other loaded shapes.

now I'm pretty sure that until mid-December 2017 I could work without problems up to the 1: 600 scale.

in the attached photos you can see the problem explained above quite clearly.

Thanks for your time, greetings

Daniele

![scale 1 1100](https://user-images.githubusercontent.com/35215636/34662479-4eda60ec-f451-11e7-9519-ea97454be124.jpg)
![scale 1 1150](https://user-images.githubusercontent.com/35215636/34662480-4ef3d180-f451-11e7-8c97-560a8fd660d7.jpg)

**Comment by HusseinKabbout** [comment]
This issue will be closed, because the qgis2 version of this plugin is not maintained anymore.
