### ISSUE TITLE
Distance measurement Tool does not work with OpenStreetMap

### ISSUE THREAD

**Issue by sdemarge** [sourcepole/qgis-openlayers-plugin#42]
I do not know if this is a problem related to the plugin of CRS management or the Distance Tool in QGIS.

Here is the scenario
When I use the Distance Tool to measure a distance that I know is 10km on a map, the distance tool give me a value of 3,000 km and 16,000km  Moving the cursor just a ittle causes the value to fluctuate wildly.
I am using QGIS2.14 on Windows 64.
I have loaded a singe layer with OpenStreetMap.  The layer loads with CRS= WGS/Pseudo Mercator EPSG 3857 and is left unchanged.
I set automatic "on the fly CRS trasnformation" and set the project CRS to UTM-18.
I zoom into an area I know, 
The scale dialog says 1:100,000 and this appears correct, also when I move the cursor a distance that I know is 10km the coordinates change by 10,000m as expected.
The Distance Tool and likely other features get the wrong distance.

Sylvain

**Comment by HusseinKabbout** [comment]
This issue will be closed, because the qgis2 version of this plugin is not maintained anymore.
