### ISSUE TITLE
'QPyNullVariant' object has no attribute '__getitem__' MacOS 

### ISSUE THREAD

**Issue by sflorea** [sourcepole/qgis-openlayers-plugin#47]
Getting a _"This plugin is broken"_ message when installing plugin. 

`'QPyNullVariant' object has no attribute '__getitem__'` 

* MacOS 10.13.3
* QGIS 2.18.15
* Python 2.7.10

**Comment by pka** [comment]
Do you have the full error message (with line numbers)?

**Comment by sflorea** [comment]
There is no more information than this message when I install and reinstall the plugin.
[
![error](https://user-images.githubusercontent.com/880403/37255522-17cb6480-2524-11e8-9d04-26e535a6909e.jpeg)
](url)

Is there a way to instantiate the plugin in debug mode? It is installed under `~/.qgis2/python/plugins/` and is listed in the `qgis.utils._plugin_modules` set from the console.

**Comment by cl5** [comment]
I'm having same problem - any way of fixing it?

**Comment by cl5** [comment]
I reinstalled python modules and plug ins then  loaded ok

**Comment by Rabscuttler** [comment]
@cl5 can you please give any more information on what you did? 
Having the same problem.

**Comment by HusseinKabbout** [comment]
This issue will be closed, because the qgis2 version of this plugin is not maintained anymore.
