### ISSUE TITLE
Issues displaying Google Satellite

### ISSUE THREAD

**Issue by DEdeder** [sourcepole/qgis-openlayers-plugin#61]
QGIS 2.18.12
OpenLayers 1.4.8
Adding a Google Satellite Layer gives me the error 
>This page can't load Google Maps correctly.
![grafik](https://user-images.githubusercontent.com/43748718/46288510-3d53ed00-c586-11e8-9688-957b224f468c.png)

Presumably there's something wrong with the Google API. Could be a pricing problem: [https://cloud.google.com/maps-platform/pricing/](url)
[https://developers.google.com/maps/documentation/javascript/error-messages?utm_source=maps_js&utm_medium=degraded&utm_campaign=billing#api-key-and-billing-errors](url)

**Comment by arcieror** [comment]
Did you have solved the problem? I have the same since few days!

**Comment by DEdeder** [comment]
@arcieror 
It seems like you need to get your own Google API key
![grafik](https://user-images.githubusercontent.com/43748718/46422038-c4929380-c733-11e8-9569-b835a6843828.png)
Never noticed the menu option before. I'd speculate that Google changed their billing policies to increase their income – and I wonder if the plugin used to share one common key for all users?
If you want to order your own API key, have a look at [https://developers.google.com/maps](url), but as always: have your credit card info ready ...

**Comment by DEdeder** [comment]
> 
> 
> @arcieror
> It seems like you need to get your own Google API key
> ![grafik](https://user-images.githubusercontent.com/43748718/46422038-c4929380-c733-11e8-9569-b835a6843828.png)
> Never noticed the menu option before. I'd speculate that Google changed their billing policies to increase their income – and I wonder if the plugin used to share one common key for all users?
> If you want to order your own API key, have a look at [https://developers.google.com/maps](url), but as always: have your credit card info ready ...

Also @gustavobarberan0

**Comment by HusseinKabbout** [comment]
As @DEdeder pointed out, you need an Google Maps API key for the maps to work. It has nothing to do with the plugin itself.

**Comment by HusseinKabbout** [comment]
I will be closing this issue, because it's not a plugin issue but a Google Maps API Key issue. For more information about how to get the API Key, visit https://developers.google.com/maps/documentation/javascript/get-api-key.
